---
- name: Install openvpn on Unbuntu
  hosts: all
  become: true

  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install openvpn
    apt:
      name: openvpn
      state: latest
