---
- name: Deploy kylemanna/openvpn (OpenVPN in a container)
  hosts: all

  vars:
    OVPN_DATA: ovpn-data-kylemanna
    # PKI_PASSWORD: SomeP@$$w0rd
    COMMON_NAME: openvpn
    SERVER_ADDRESS: "{{ ansible_host }}"

  vars_prompt:
    - name: PKI_PASSWORD
      prompt: Enter CA Key Passphrase

  tasks:

  - name: Show host's ip
    debug:
      msg: "{{ ansible_host }}"

  - name: Create a volume
    docker_volume:
      name: "{{ OVPN_DATA }}"

  - name: Generate config and set the server address
    community.docker.docker_container:
      name: generate_ovpn_config
      image: kylemanna/openvpn
      volumes: 
        - "{{ OVPN_DATA }}:/etc/openvpn"
      command: "ovpn_genconfig -u udp://{{ SERVER_ADDRESS }}"
      auto_remove: true

  # Requires python pexpect module installed on the host

  - name: Create PKI
    ansible.builtin.expect:
      command: docker run -v {{ OVPN_DATA }}:/etc/openvpn --rm -it kylemanna/openvpn ovpn_initpki
      responses:
        Confirm removal: "no"
        Enter New CA Key Passphrase: "{{ PKI_PASSWORD }}"
        \[Easy-RSA CA\]: "{{ COMMON_NAME }}"
        Enter pass phrase for /etc/openvpn/pki/private/ca.key: "{{ PKI_PASSWORD }}"
      timeout: 60
    ignore_errors: true

  - name: Start OpenVPN server process in the container
    community.docker.docker_container:
      name: openvpn_kylemanna
      image: kylemanna/openvpn
      state: started
      ports:
        - 1194:1194/udp
      volumes: 
        - "{{ OVPN_DATA }}:/etc/openvpn"
      capabilities: NET_ADMIN